apiVersion: v1
kind: Pod
metadata:
  name: dbfarmacia
  labels:
    app: api-pod
spec:
  containers:
    - name: mysql
      image: mysql:latest
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: db-configmap